kind: Pod
apiVersion: v1
metadata: 
  name: env 
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: devops
      value: "kubernetes"
    - name: course 
      value: "kubernetes"
