kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    # envFrom:
    #   - secretRef:
    #       name: secrets
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: secrets
          key: username