kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: username
      valueFrom:
        secretMapKeyRef:
          name: secrets
          key: username
    - name: password
      valueFrom:
        secretMapKeyRef:
          name: secrets
          key: password