apiVersion: v1
kind: Service
metadata:
  name: clusterIP
spec:
  selector:
    name: nginx
    course: devops
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # targetport