apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    name: nginx
    course: devops
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # targetport
      nodePort: 30422