kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    course: devops
    tool: kubernetes
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      course: devops
      tool: kubernetes
      environment: dev
  template:
    metadata:
      labels:
        course: devops
        tool: kubernetes
        environment: dev
      spec:
        containers:
        - name: nginx
          image: nginx
