kind: ReplicaSet
apiVersion: app/v1
metadata:
  name: replicaset 
  labels:
    course: devops
    tool: kubernetes
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      course: devops
      tool: kubernetes
      environment: dev
  templates:
  metadata:
    name: nginx
    labels:
      course: devops
      tool: kubernetes
      environment: dev
  containers:
  - name: nginx
    image: nginx
  

