kind: Deployment
apiVersion: app/v1
metadata:
  name: deployment 
  labels:
    name: devops
    tool: kubernetes
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      name: devops
      tool: kubernetes
      environment: dev
  templates:
    metadata:
      labels:
        name: devops
        tool: kubernetes
        environment: dev
      spec:
        containers:
        - name: nginx
          image: nginx    